// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import frc.robot.subsystems.DriveSubsystem;
import frc.robot.subsystems.LimelightSubsystem;
import frc.robot.subsystems.ShooterSubsystem;
import frc.robot.codebases.AutoDrive;
import frc.robot.codebases.PositionChecker;




public class AssistedShoot extends Command {

    private final DriveSubsystem m_driveSubsystem;
    private final ShooterSubsystem m_shooterSubsystem;
    private final LimelightSubsystem m_limelightSubsystem;

    private double[] desiredPose = new double[4];
    private double desiredX;
    private double desiredY;
    private double desiredTheta;
    private double desiredSpeed;

    private double targetDistance;

    private double m_tX;
    private double m_tY;

    private Pose2d m_botPose;
    

    private final double poseMargin;
    private final double thetaMargin;
    
    private boolean shootingPhase;

    private final AutoDrive m_driver;
    private final PositionChecker m_poseChecker;

    public AssistedShoot(DriveSubsystem driveSubsystem, ShooterSubsystem shooterSubsystem, LimelightSubsystem limelightSubsystem) {

        m_driveSubsystem = driveSubsystem;
        m_shooterSubsystem = shooterSubsystem;
        m_limelightSubsystem = limelightSubsystem;
        addRequirements(m_driveSubsystem, m_shooterSubsystem);   
        
        poseMargin = (.1)/2; //in meters
        thetaMargin = (.5)/2; //in degrees

        m_driver = new AutoDrive(driveSubsystem);
        m_poseChecker = new PositionChecker(driveSubsystem);

    }

    
    @Override
    public void initialize() {

        if(assistNeeded()) {

        }

    }

    public boolean assistNeeded(){
        boolean assistNeeded;

      

        //alignment of the limelight 
        m_tX = m_limelightSubsystem.getX3d();
        m_tY = m_limelightSubsystem.getY3d();

        //calucalutes the offset from the desired state and current state of the robot
       // m_botPose = m_limelightSubsystem.getPose2d()
       double m_xDiff = m_botPose.getX() - desiredX;
       double m_yDiff = m_botPose.getY() - desiredY;
       double m_thetaDiff = m_botPose.getRotation().getDegrees() - desiredTheta;

       //checks if the ofset from the desired shooting state is within the margin of error
       if (-poseMargin < m_xDiff && m_xDiff < poseMargin &&
           -poseMargin < m_yDiff && m_yDiff < poseMargin &&
           -thetaMargin < m_thetaDiff && m_thetaDiff < thetaMargin) {
            
            assistNeeded = false; //It is aligned --> No adjustment needed
       } else {
            assistNeeded = false; //It is not aligned --> adjustment Needed
       }

        return assistNeeded;
    }



    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        //check is limelight is aimed correctly 
        if (m_driver.getSwerveController().isFinished()) {
        
            if (!assistNeeded()) {
            //    shoot(); //not a method yet!!!!<------
            }

        }
        
        
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return false;
    }

    @Override
    public boolean runsWhenDisabled() {
      
        return false;

     
    }
}
