// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import frc.robot.subsystems.DriveSubsystem;
import frc.robot.subsystems.LimelightSubsystem;
import frc.robot.subsystems.ShooterSubsystem;
import frc.robot.codebases.AutoDrive;
import frc.robot.codebases.PositionChecker;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.DriverStation;




public class AssistedShoot extends Command {

    private final DriveSubsystem drive;
    private final LimelightSubsystem limelight;

    private boolean redAlliance;
    private Alliance alliance;

    // --------------------
    // PID Controllers
    // --------------------
    private final PIDController xController;     // forward/back
    private final PIDController yController;     // strafe
    private final PIDController yawController;   // rotation

    // PID tuning variables (adjust as needed)
    private final double kP_X = 0.5;   // forward/back speed gain
    private final double kP_Y = 0.5;   // strafe speed gain
    private final double kP_Yaw = 0.03; // rotation gain (degrees)

    private final double xTolerance = 0.01; // meters/sec tolerance or arbitrary units
    private final double yTolerance = 0.01;
    private final double yawTolerance = 1.0; // degrees

    public AssistedShoot(
          DriveSubsystem drive,
            LimelightSubsystem limelight) {
        this.drive = drive;
        this.limelight = limelight;

        // PID controllers using limelight setpoints
        this.xController = new PIDController(kP_X, 0.0, 0.0);
        this.yController = new PIDController(kP_Y, 0.0, 0.0);
        this.yawController = new PIDController(kP_Yaw, 0.0, 0.0);

        this.xController.setTolerance(xTolerance);
        this.yController.setTolerance(yTolerance);
        this.yawController.setTolerance(yawTolerance);

        addRequirements(drive);

          
        if (alliance == Alliance.Red) {
            redAlliance = true;
        } else {
            redAlliance = false;
        }
    

    }

    @Override
    public void initialize() {

        
    }



    // Called every time the scheduler runs while the command is scheduled.
     @Override
    public void execute() {
       // Only align if the target for our alliance is visible
        if (!limelight.hasTarget(redAlliance)) {
            drive.driveRobotRelative(new ChassisSpeeds(0, 0, 0));
            return;
        }

        // Compute PID outputs
        // Limelight X/Y are usually in degrees, you may need to scale to meters/sec
        double vx = xController.calculate(limelight.getTy(), limelight.tySetpoint);
        double vy = yController.calculate(limelight.getTx(), limelight.txSetpoint);
        double omega = yawController.calculate(limelight.getYaw(), limelight.yawSetpoint);

        // Optional: limit max speedju
        double maxSpeed = 2.0; // m/s
        vx = Math.max(Math.min(vx, maxSpeed), -maxSpeed);
        vy = Math.max(Math.min(vy, maxSpeed), -maxSpeed);
        omega = Math.max(Math.min(omega, 2.0), -2.0); // rad/s or units consistent with driveRobotRelative

        // Drive the robot (robot-relative speeds)
        drive.driveRobotRelative(new ChassisSpeeds(vx, vy, omega));
    }

    @Override
    public boolean isFinished() {
        return xController.atSetpoint() && yController.atSetpoint() && yawController.atSetpoint();
    }

    @Override
    public void end(boolean interrupted) {
        drive.driveRobotRelative(new ChassisSpeeds(0, 0, 0));
    }
}
