// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import java.util.function.DoubleSupplier;

import frc.robot.subsystems.ConveyerSubsystem;
import frc.robot.subsystems.ShooterSubsystem;
import frc.robot.Constants.ConveyerConstants;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class AutoShoot extends Command {

    private final ShooterSubsystem m_shootSubsystem;
    private final ConveyerSubsystem m_conveySubsystem;
    private final double m_speed;
    private Timer m_timer = new Timer();

   /**
    * First runs the shooter to reach speed, then shoots by turning on the conveyer
    * 
    * @param shootSubsystem
    * @param conveySubsystem
    * @param speed speed you want to shoot at
    *
    */
    public AutoShoot(ShooterSubsystem shootSubsystem, ConveyerSubsystem conveySubsystem, double speed) {

        m_speed = speed;
        m_shootSubsystem = shootSubsystem;
        m_conveySubsystem = conveySubsystem;
        addRequirements(m_shootSubsystem, m_conveySubsystem);      
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
       m_timer.reset();
       m_timer.start();
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        
        if (!m_timer.hasElapsed(7))
            m_shootSubsystem.setShooterSpeed(m_speed);
        
        
        if (m_timer.hasElapsed(2) && !m_timer.hasElapsed(7)) { //I want to fix this so it does it when the shooter reaches a certain speed
            m_conveySubsystem.setConveyerSpeed(ConveyerConstants.kConveyerSpeed);
        }

        if (m_timer.hasElapsed(7)){ //I want to fix this so it does it when the shooter reaches a certain speed
            m_shootSubsystem.stopShooter(); 
            m_conveySubsystem.stopConveyer();
        }
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
        m_shootSubsystem.stopShooter(); 
        m_conveySubsystem.stopConveyer();
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return false;
    }

    @Override
    public boolean runsWhenDisabled() {
     
        return false;

      
    }
}
