// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;

import edu.wpi.first.math.MathUtil;
import edu.wpi.first.wpilibj2.command.Command;

import frc.robot.codebases.controllers.Controller;
import java.util.function.DoubleSupplier;

import frc.robot.Constants.OIConstants;
import frc.robot.subsystems.DriveSubsystem;
import frc.robot.Constants.DriveConstants;;


/**
 *
 */
public class Drive extends Command {

    private final DriveSubsystem m_driveSubsystem;
    private final Controller m_controller;


    public Drive(DriveSubsystem driveSubsystem, Controller controller) {

    
        m_controller = controller;
        m_driveSubsystem = driveSubsystem;
        addRequirements(m_driveSubsystem);    

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
         m_driveSubsystem.drive(
                -MathUtil.applyDeadband(m_controller.getLeftY(), OIConstants.kDriveDeadband),
                -MathUtil.applyDeadband(m_controller.getLeftX(), OIConstants.kDriveDeadband),
                -MathUtil.applyDeadband(m_controller.getRightX(), OIConstants.kDriveDeadband), //rightX
                DriveConstants.kFeildOreiented
            );
        
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
         m_driveSubsystem.drive(0,0,0,true);
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return false;
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
