// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.Command;
import java.util.function.DoubleSupplier;
import frc.robot.subsystems.FolderSubsystem;
import frc.robot.Constants.FolderConstants;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class Fold extends Command {

    private final FolderSubsystem m_subsystem;
    private final boolean m_direction;//true is up, false is down

    /**
     * Used for both up and down for the climber, specify which direction using the boolean parameter.
     * @param subsystem
     * @param direction in is True, out is False
     */
    public Fold(FolderSubsystem subsystem, boolean direction ) {

        m_direction = direction;
        m_subsystem = subsystem;
        addRequirements(m_subsystem);    

    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
       
       if (m_direction) { //up
            m_subsystem.setFolderSpeed(FolderConstants.kFoldUpSpeed);//up
        } else {
            m_subsystem.setFolderSpeed(FolderConstants.kFoldDownSpeed);//down
        }
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
        m_subsystem.stopFolder(); 
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return false;
    }

    @Override
    public boolean runsWhenDisabled() {
     
        return false;

      
    }
}
